/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.11 cartoon_car.gltf --transform 
Files: cartoon_car.gltf [390.6KB] > cartoon_car-transformed.glb [458.1KB] (-17%)
Author: applejuice159 (https://sketchfab.com/applejuice159)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cartoon-car-019eda129767452cae32aee9a4bd91ef
Title: Cartoon Car
*/

import { useGLTF } from "@react-three/drei";

export default function Model(props: any) {
  const { nodes, materials }: any = useGLTF("/cartoon_car-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_7.geometry}
        material={materials.PaletteMaterial001}
        position={[-1.373, 0.784, -0.03]}
        rotation={[0, -0.006, 0]}
        scale={1.058}
      />
      <mesh
        geometry={nodes.Object_8.geometry}
        material={materials.PaletteMaterial002}
        position={[-1.373, 0.784, -0.03]}
        rotation={[0, -0.006, 0]}
        scale={1.058}
      />
      <mesh
        geometry={nodes.Object_14.geometry}
        material={materials.PaletteMaterial003}
        position={[-1.373, 0.784, -0.03]}
        rotation={[0, -0.006, 0]}
        scale={1.058}
      />
      <mesh
        geometry={nodes.Object_15.geometry}
        material={materials.PaletteMaterial004}
        position={[-1.373, 0.784, -0.03]}
        rotation={[0, -0.006, 0]}
        scale={1.058}
      />
      <mesh
        geometry={nodes.Object_17.geometry}
        material={materials.PaletteMaterial005}
        position={[-1.373, 0.784, -0.03]}
        rotation={[0, -0.006, 0]}
        scale={1.058}
      />
    </group>
  );
}

useGLTF.preload("/cartoon_car-transformed.glb");
