/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.11 mini_macbook_pro.gltf --transform 
Files: mini_macbook_pro.gltf [856.77KB] > mini_macbook_pro-transformed.glb [170.46KB] (80%)
Author: Bastien Genbrugge (https://sketchfab.com/bastienBGR)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mini-macbook-pro-2b054523279747c8b5b2e5ed9ea7b311
Title: Mini MacBook Pro
*/

import { useGLTF } from "@react-three/drei";

export default function Model(props: any) {
  const { nodes, materials }: any = useGLTF(
    "/mini_macbook_pro-transformed.glb"
  );

  // Set the new color for the "MacBook.1" material
  materials["MacBook.1"].color.set("#ff9900"); // Orange color

  // Set the new color for the "material" material
  materials.material.color.set("#00ff00"); // Green color

  // Set the new color for the "Mat_0" material
  materials.Mat_0.color.set("#0000ff"); // Blue color

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.MacBook_1_MacBook1_0.geometry}
        material={materials["MacBook.1"]}
        position={[8.578, 13.853, 133.996]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        geometry={nodes.Muis_1_Mat_2.geometry}
        material={materials.material}
        position={[-8.578, -13.853, -133.996]}
        rotation={[Math.PI, -0.281, Math.PI]}
      />
      <mesh
        geometry={nodes.Muis_1_Mat_0.geometry}
        material={materials.Mat_0}
        position={[-8.578, -13.853, -133.996]}
        rotation={[Math.PI, -0.281, Math.PI]}
      />
    </group>
  );
}

useGLTF.preload("/mini_macbook_pro-transformed.glb");
