/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.11 retro_computer.gltf --transform 
Files: retro_computer.gltf [895.95KB] > retro_computer-transformed.glb [248.68KB] (72%)
Author: dogflesh (https://sketchfab.com/dogflesh)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/retro-computer-9439cb5e09cc44caa63dfbfb299df45f
Title: Retro computer
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";

export default function Model(props: any) {
  const { nodes, materials }: any = useGLTF("/retro_computer-transformed.glb");

  // Clone the materials.None material
  const retroMaterial = materials.None.clone();

  // Set retro-style color
  retroMaterial.color.set("#d48441"); // Retro orange color

  // Adjust material properties
  retroMaterial.roughness = 0.2; // Increase for a less shiny look
  retroMaterial.metalness = 0.4; // Reduce for a more matte look

  // You can also add textures to enhance the retro appearance
  const textureLoader = new THREE.TextureLoader();
  const retroTexture = textureLoader.load("/path/to/None_diffuse");
  retroMaterial.map = retroTexture; // Apply the texture

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_2.geometry}
        material={retroMaterial}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}
