/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.11 sad_toaster.gltf --transform 
Files: sad_toaster.gltf [3.28MB] > sad_toaster-transformed.glb [516.09KB] (84%)
Author: Tasha.Lime (https://sketchfab.com/tasha.lime)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/sad-toaster-9b158486dfa1490eb9157966321283a0
Title: Sad toaster
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props: any) {
  const { nodes, materials }: any = useGLTF("/sad_toaster-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_2.geometry}
        material={materials["Material.001"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_3.geometry}
        material={materials["Material.002"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/sad_toaster-transformed.glb");
